name: Deploy
on:
  push:
    branches:
      - main

permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Configure Git Credentials
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
      - uses: actions/setup-node@v3
        with:
          node-version: 20
      - uses: pnpm/action-setup@v4
        with:
          version: 9
      - run: pnpm install --frozen-lockfile
      - run: npm run build:packages
      - run: rm -rf packages node_modules .gitignore
      - run: git init
      - run: git add -A
      - run: git commit -m "Deploy"
      - run: git push -f git@github.com:wataruoguchi/poc-spa-gh-pages.git main:gh-pages
